sudo: false
language: groovy
jdk: oraclejdk8
env: TERM=dumb
dist: trusty
cache:
  directories:
  - $HOME/.gradle

branches:
  except:
  - /^v\d+\.\d+\.\d+$/
before_install:
- chmod +x gradlew
- git fetch
- git config user.email "rzabini@@users.noreply.github.com"
- git config user.name "Travis-CI"
- git config url.https://.insteadOf git://
- git checkout -qf $TRAVIS_BRANCH
# skip default gradlew assemble
install:
- echo "skip default gradlew assemble"
script:
- './gradlew clean test --info --stacktrace  --tests com.github.rzabini.org.approvaltests.spock.VerifySpecification'

after_success:
- ./gradlew jacocoTestReport
